### ISSUE TITLE
Red exclamation point on project.

### ISSUE THREAD

**Issue by twlkyao** [devpack/android-python27#1]
After I import the apk project, there is a red exclamation point on the project, I have removed all the libs and added them,  without success, there is no obvious sign on teh build path, how to fix this?
![1](https://cloud.githubusercontent.com/assets/1272629/3065797/48b448c6-e268-11e3-8693-662f8ffd8791.jpg)

**Comment by devpack** [comment]
Try this:
1. Right click on the project -> Android tools -> Fix project properties
2. Java Compiler -> Building -> Build path problems - set Incomplete build path: to Warning
3. Project -> Clean (twice)

**Comment by twlkyao** [comment]
Problem solved, thanks.
