### ISSUE TITLE
Failed to chmod: android.system.ErrnoException: chmod failed: EPERM (Operation not permitted)

### ISSUE THREAD

**Issue by ghost** [devpack/android-python27#7]
I tried to install the apk in my android device (API 21).
The files unzip with success but when it tries to chmod it fails. For example:

Unzip extracted /storage/emulated/0/com.android.python27/extras/python/xml/etree/ElementPath.py
01-18 17:08:54.403 20996-21039/com.android.python27 W/FileUtils: Failed to chmod(/storage/emulated/0/com.android.python27/extras/python/xml/etree/ElementTree.py): android.system.ErrnoException: chmod failed: EPERM (Operation not permitted)

These happens for all python extras. When I try to install the apk in my another android (API 16) device it chmod with success. Is there a way to solve this issue?

**Comment by ghost** [comment]
Well it seems that you can't chmod because the storage is emulated (emulated storage systems normally use FAT file systems, which do not support chmod).
The only way to solve this issue is to change the installation path using a separate partition with different file system (ext).
Unfortunatelly most modern android devices use this kind of file system. As a result it is impossible to install with success the current apk without some changes.

**Comment by michaelrinderle** [comment]
i fixed this bug. ---> https://github.com/ainsophical/droid-python

**Comment by ghost** [comment]
Thank you it works...I really appreciate your help!!!

2016-03-02 3:40 GMT+02:00 michael notifications@github.com:
